os: linux
dist: bionic
language: go
go:
  - "1.17.2"
services:
  - docker
addons:
  apt:
    packages:
      - pigz

env:
  global:
    - GO111MODULE=on
    - ALLOW_FAIL=false
    - ROSETTA_MAINTAINER_KEYS="8f94311b0d7422b170ae0cc271ba5ca94e686cf7 219f55740bbf7a1ce368ba45fb7053ce4991b669 FC3388A460ACFAB04E8328C07BB2A1D2CFDFCD2C"
    - ZEND_MAINTAINER_KEYS="219f55740bbf7a1ce368ba45fb7053ce4991b669 FC3388A460ACFAB04E8328C07BB2A1D2CFDFCD2C 1754AAB85B4A25165464478F670FC45BE6CA359F"
    - ZEN_COMMITTISH=v5.0.5
    - DOCKER_IMAGE_NAME=zencash/rosetta-zen

# TODO remove || true
install: make deps || true

# TODO fix failures
jobs:
  allow_failures:
    env:
      - ALLOW_FAIL=true
  include:
    - stage: Tests
      script: make test
    - stage: Tests
      env:
        - ALLOW_FAIL=true
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
        - make lint
    - stage: Tests
      env:
        - ALLOW_FAIL=true
      script: make check-license
    - stage: Tests
      env:
        - ALLOW_FAIL=true
      script: make check-format
    - stage: Tests
      env:
        - ALLOW_FAIL=true
      script: make coverage
    - stage: Tests
      env:
        - ALLOW_FAIL=true
      script: make salus
    - stage: Build
      vm:
        size: 2x-large
      script:
        - source ci/setup_env.sh
        - if [ ! -z "${version}" ]; then make build-release; else make build-local; fi

deploy:
  edge: true
  provider: releases
  draft: false
  overwrite: true
  token: "${GITHUB_TOKEN}"
  release_notes: "Release ${version}"
  file_glob: false
  file:
    - "./rosetta-zen-${version}.tar.gz"
  cleanup: false
  on:
    tags: true
    condition: '! -z "${version}"'
